SampleMvcCodeSample/Models/AccountViewModels.cs
using System.ComponentModel.DataAnnotations;

namespace SampleMvcCodeSample.Models
{
    public class ExternalLoginConfirmationViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }
    }

    public class ManageUserViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class LoginViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }

    public class RegisterViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
}

SampleMvcCodeSample/Models/IdentityModels.cs
using Microsoft.AspNet.Identity.EntityFramework;

namespace SampleMvcCodeSample.Models
{
    // You can add profile data for the user by adding more properties to your ApplicationUser class, please visit http://go.microsoft.com/fwlink/?LinkID=317594 to learn more.
    public class ApplicationUser : IdentityUser
    {
    }

    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext()
            : base("DefaultConnection")
        {
        }
    }
}

SampleMvcCodeSample/Controllers/SoccerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SampleMvcCodeSample.Controllers
{
    public class SoccerController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

SampleMvcCodeSample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My Sample Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Soccer Stats", "Index", "Soccer", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Soccer")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Sample Application</p>
        </footer>
    </div>

    
    @RenderSection("scripts", required: false)
</body>
</html>

SampleMvcCodeSample/Views/Soccer/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <title>Soccer App</title>
    <script type="text/javascript" src="/Scripts/SoccerApp/app.js"></script>
    <script type="text/javascript" src="/Scripts/SoccerApp/dataService.js"></script>
</head>

<body ng-app="SoccerApp" ng-controller="SoccerController">
    <h1>Chicago Fire Soccer Players</h1>
    <select id="selPlayers" ng-change="getPlayerData(PlayerListSelected)" ng-model="PlayerListSelected" ng-options="opt.FullName for opt in PlayerList">
        <option value="">Select Player</option>
    </select>
    <div id="divPlayerList" ng-model="PlayerList" ng-show="!isDetail">
        <table>
            <thead>
                <tr>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody>
                <tr ng-repeat="p in PlayerList">
                    <td>{{p.FullName}}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div id="divPlayerDetail" ng-model="PlayerDetail" ng-show="isDetail">
        <div>Name: {{PlayerDetail.FullName}}</div>
        <div>Age: {{PlayerDetail.Age}}</div>
        <div>Height: {{PlayerDetail.Height}}</div>
        <div>Weight: {{PlayerDetail.Weight}}</div>
        <div>Position: {{PlayerDetail.Position}}</div>
        <div>Jersey Number: {{PlayerDetail.JerseyNumber}}</div>
        <div>
            Stats:
            <table>
                <thead>
                    <tr>
                        <th>Year</th>
                        <th>Club</th>
                        <th>Games Played</th>
                        <th>Minutes</th>
                        <th>Shots</th>
                        <th>Goals</th>
                    </tr>
                </thead>
                <tbody>
                    <tr ng-repeat="p in PlayerDetail.Stats">
                        <td>{{p.Year}}</td>
                        <td>{{p.Club}}</td>
                        <td>{{p.GamesPlayed}}</td>
                        <td>{{p.Minutes}}</td>
                        <td>{{p.Shots}}</td>
                        <td>{{p.Goals}}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</body>